using DataAccessLayer.Contexts;
using DataAccessLayer.Entities;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;

namespace DataAccessLayer.Utils
{
    public class CreateDatabase
    {
        public static void InitDatabase()
        {
            using (var ctx = new NorthwindContext())
            {

                var boolean = false;
                Room rec = new Room { Name = "Reception", IsDeleted = boolean };
                Room r = new Room { Name = "Red", IsDeleted = boolean };
                Room b = new Room { Name = "Blue", IsDeleted = boolean };
                Room o = new Room { Name = "Orange", IsDeleted = boolean };
                Room p = new Room { Name = "Pink", IsDeleted = boolean };
                Room black = new Room { Name = "Black", IsDeleted = boolean };
                Room w = new Room { Name = "White", IsDeleted = boolean };
                Room g = new Room { Name = "Green", IsDeleted = boolean };
                Room y = new Room { Name = "Yellow", IsDeleted = boolean };

                ctx.Rooms.Add(rec);
                ctx.Rooms.Add(r);
                ctx.Rooms.Add(b);
                ctx.Rooms.Add(o);
                ctx.Rooms.Add(p);
                ctx.Rooms.Add(black);
                ctx.Rooms.Add(w);
                ctx.Rooms.Add(g);
                ctx.Rooms.Add(y);

                Employee e1 = new Employee { Name = "Admin", Password = "1234", IsDeleted = boolean, Department = "Admin", WorkPlace = rec, StartHour = 9, EndHour = 17, Days = "H_K_SZE_CS_P_SZO" };
                Employee e2 = new Employee { Name = "kasszas_erzsi", Password = "186234", IsDeleted = boolean, Department = "Reception", WorkPlace = rec, StartHour = 14, EndHour = 20, Days = "H_K_SZE_CS_P_SZO" };
                Employee e3 = new Employee { Name = "mancika", Password = "18234", IsDeleted = boolean, Department = "Reception", WorkPlace = rec, StartHour = 14, EndHour = 20, Days = "H_K_SZE_CS_P_SZO" };
                Employee e4 = new Employee { Name = "katy96", Password = "12734", IsDeleted = boolean, Department = "Fitness Trainer", WorkPlace = o, StartHour = 8, EndHour = 14, Days = "H_K_SZE_CS_P_SZO" };
                Employee e5 = new Employee { Name = "adamkis", Password = "17234", IsDeleted = boolean, Department = "Fitness Trainer", WorkPlace = p, StartHour = 8, EndHour = 14, Days = "H_K_SZE_CS_P_SZO" };
                Employee e6 = new Employee { Name = "mark87", Password = "12347", IsDeleted = boolean, Department = "Fitness Trainer", WorkPlace = black, StartHour = 8, EndHour = 14, Days = "H_K_SZE_CS_P_SZO" };
                Employee e7 = new Employee { Name = "peter45", Password = "158234", IsDeleted = boolean, Department = "Fitness Trainer", WorkPlace = w, StartHour = 8, EndHour = 14, Days = "H_K_SZE_CS_P_SZO" };
                Employee e8 = new Employee { Name = "stean56", Password = "12834", IsDeleted = boolean, Department = "Fitness Trainer", WorkPlace = g, StartHour = 8, EndHour = 14, Days = "H_K_SZE_CS_P_SZO" };
                Employee e9 = new Employee { Name = "loise37", Password = "18234", IsDeleted = boolean, Department = "Fitness Trainer", WorkPlace = y, StartHour = 8, EndHour = 14, Days = "H_K_SZE_CS_P_SZO" };
                Employee e10 = new Employee { Name = "corina21", Password = "182234", IsDeleted = boolean, Department = "Gym Trainer", WorkPlace = r, StartHour = 8, EndHour = 14, Days = "H_K_SZE_CS_P_SZO" };
                Employee e11 = new Employee { Name = "helen57", Password = "182334", IsDeleted = boolean, Department = "Gym Trainer", WorkPlace = b, StartHour = 8, EndHour = 14, Days = "H_K_SZE_CS_P_SZO" };
                Employee e12 = new Employee { Name = "annie68", Password = "1824534", IsDeleted = boolean, Department = "Gym Trainer", WorkPlace = o, StartHour = 8, EndHour = 14, Days = "H_K_SZE_CS_P_SZO" };
                Employee e13 = new Employee { Name = "brian24", Password = "182834", IsDeleted = boolean, Department = "Gym Trainer", WorkPlace = p, StartHour = 8, EndHour = 14, Days = "H_K_SZE_CS_P_SZO" };
                Employee e14 = new Employee { Name = "david34", Password = "186234", IsDeleted = boolean, Department = "Gym Trainer", WorkPlace = black, StartHour = 8, EndHour = 14, Days = "H_K_SZE_CS_P_SZO" };
                Employee e15 = new Employee { Name = "stephen_hawking", Password = "186234", IsDeleted = boolean, Department = "Gym Trainer", WorkPlace = w, StartHour = 8, EndHour = 14, Days = "H_K_SZE_CS_P_SZO" };
                Employee e16 = new Employee { Name = "steve45", Password = "186234", IsDeleted = boolean, Department = "Gym Trainer", WorkPlace = g, StartHour = 8, EndHour = 14, Days = "H_K_SZE_CS_P_SZO" };
                Employee e17 = new Employee { Name = "alexa247", Password = "18234", IsDeleted = boolean, Department = "Gym Trainer", WorkPlace = y, StartHour = 8, EndHour = 14, Days = "H_K_SZE_CS_P_SZO" };
                Employee e18 = new Employee { Name = "gerard42", Password = "4411", IsDeleted = boolean, Department = "Fitness Trainer", WorkPlace = r, StartHour = 14, EndHour = 20, Days = "H_K_SZE_CS_P_SZO" };
                Employee e19 = new Employee { Name = "sue75", Password = "12354", IsDeleted = boolean, Department = "Fitness Trainer", WorkPlace = b, StartHour = 14, EndHour = 20, Days = "H_K_SZE_CS_P_SZO" };
                Employee e20 = new Employee { Name = "clayton42", Password = "12734", IsDeleted = boolean, Department = "Fitness Trainer", WorkPlace = o, StartHour = 14, EndHour = 20, Days = "H_K_SZE_CS_P_SZO" };
                Employee e21 = new Employee { Name = "dominica", Password = "17234", IsDeleted = boolean, Department = "Fitness Trainer", WorkPlace = p, StartHour = 14, EndHour = 20, Days = "H_K_SZE_CS_P_SZO" };
                Employee e22 = new Employee { Name = "victor333", Password = "12347", IsDeleted = boolean, Department = "Fitness Trainer", WorkPlace = black, StartHour = 14, EndHour = 20, Days = "H_K_SZE_CS_P_SZO" };
                Employee e23 = new Employee { Name = "petra548", Password = "158234", IsDeleted = boolean, Department = "Fitness Trainer", WorkPlace = w, StartHour = 14, EndHour = 20, Days = "H_K_SZE_CS_P_SZO" };
                Employee e24 = new Employee { Name = "stefan242", Password = "12834", IsDeleted = boolean, Department = "Fitness Trainer", WorkPlace = g, StartHour = 14, EndHour = 20, Days = "H_K_SZE_CS_P_SZO" };
                Employee e25 = new Employee { Name = "alexis452", Password = "18234", IsDeleted = boolean, Department = "Fitness Trainer", WorkPlace = y, StartHour = 14, EndHour = 20, Days = "H_K_SZE_CS_P_SZO" };
                Employee e26 = new Employee { Name = "caroline65", Password = "182234", IsDeleted = boolean, Department = "Gym Trainer", WorkPlace = r, StartHour = 14, EndHour = 20, Days = "H_K_SZE_CS_P_SZO" };
                Employee e27 = new Employee { Name = "henriette221", Password = "182334", IsDeleted = boolean, Department = "Gym Trainer", WorkPlace = b, StartHour = 14, EndHour = 20, Days = "H_K_SZE_CS_P_SZO" };
                Employee e28 = new Employee { Name = "amy41", Password = "1824534", IsDeleted = boolean, Department = "Gym Trainer", WorkPlace = o, StartHour = 14, EndHour = 20, Days = "H_K_SZE_CS_P_SZO" };
                Employee e29 = new Employee { Name = "john42", Password = "182834", IsDeleted = boolean, Department = "Gym Trainer", WorkPlace = p, StartHour = 14, EndHour = 20, Days = "H_K_SZE_CS_P_SZO" };
                Employee e30 = new Employee { Name = "smith324", Password = "186234", IsDeleted = boolean, Department = "Gym Trainer", WorkPlace = black, StartHour = 14, EndHour = 20, Days = "H_K_SZE_CS_P_SZO" };
                Employee e31 = new Employee { Name = "agatha_christie", Password = "186234", IsDeleted = boolean, Department = "Gym Trainer", WorkPlace = w, StartHour = 14, EndHour = 20, Days = "H_K_SZE_CS_P_SZO" };
                Employee e32 = new Employee { Name = "sten_lee", Password = "186234", IsDeleted = boolean, Department = "Gym Trainer", WorkPlace = g, StartHour = 14, EndHour = 20, Days = "H_K_SZE_CS_P_SZO" };
                Employee e33 = new Employee { Name = "cho234", Password = "18234", IsDeleted = boolean, Department = "Gym Trainer", WorkPlace = y, StartHour = 14, EndHour = 20, Days = "H_K_SZE_CS_P_SZO" };
                Employee e34 = new Employee { Name = "herry54", Password = "4411", IsDeleted = boolean, Department = "Fitness Trainer", WorkPlace = r, StartHour = 8, EndHour = 14, Days = "H_K_SZE_CS_P_SZO" };
                Employee e35 = new Employee { Name = "james42", Password = "12354", IsDeleted = boolean, Department = "Fitness Trainer", WorkPlace = b, StartHour = 8, EndHour = 14, Days = "H_K_SZE_CS_P_SZO" };

                ctx.Employees.Add(e1);
                ctx.Employees.Add(e2);
                ctx.Employees.Add(e3);
                ctx.Employees.Add(e4);
                ctx.Employees.Add(e5);
                ctx.Employees.Add(e6);
                ctx.Employees.Add(e7);
                ctx.Employees.Add(e8);
                ctx.Employees.Add(e9);
                ctx.Employees.Add(e10);
                ctx.Employees.Add(e11);
                ctx.Employees.Add(e12);
                ctx.Employees.Add(e13);
                ctx.Employees.Add(e14);
                ctx.Employees.Add(e15);
                ctx.Employees.Add(e16);
                ctx.Employees.Add(e17);
                ctx.Employees.Add(e18);
                ctx.Employees.Add(e19);
                ctx.Employees.Add(e20);
                ctx.Employees.Add(e21);
                ctx.Employees.Add(e22);
                ctx.Employees.Add(e23);
                ctx.Employees.Add(e24);
                ctx.Employees.Add(e25);
                ctx.Employees.Add(e26);
                ctx.Employees.Add(e27);
                ctx.Employees.Add(e28);
                ctx.Employees.Add(e29);
                ctx.Employees.Add(e30);
                ctx.Employees.Add(e31);
                ctx.Employees.Add(e32);
                ctx.Employees.Add(e33);
                ctx.Employees.Add(e34);
                ctx.Employees.Add(e35);

                Client c1 = new Client { FirstName = "Timea", LastName = "Fulop", Phone = "742975896", Email = "fuloptimea1427@gmail.com", IsDeleted = boolean, BirthYear = 1997, InsertedDate = DateTime.Now, IdentityNumber = "2970821191291", Sex = true, Inserter = e1 };
                Client c2 = new Client { FirstName = "Adam", LastName = "Gal", Phone = "742973336", Email = "fadam@gmail.com", IsDeleted = boolean, BirthYear = 1992, InsertedDate = DateTime.Now, IdentityNumber = "2970821191292", Sex = false, Inserter = e2 };
                Client c3 = new Client { FirstName = "Geza", LastName = "Peter", Phone = "742975896", Email = "peter@gmail.com", IsDeleted = boolean, BirthYear = 1987, InsertedDate = DateTime.Now, IdentityNumber = "2970821191293", Sex = false, Inserter = e3 };
                Client c4 = new Client { FirstName = "Peter", LastName = "Kovacs", Phone = "711975896", Email = "kovacs@gmail.com", IsDeleted = boolean, BirthYear = 1940, InsertedDate = DateTime.Now, IdentityNumber = "2970821191294", Sex = false, Inserter = e4 };
                Client c5 = new Client { FirstName = "Imre", LastName = "Kelemen", Phone = "744975896", Email = "kelemen@gmail.com", IsDeleted = boolean, BirthYear = 1970, InsertedDate = DateTime.Now, IdentityNumber = "2970821191295", Sex = false, Inserter = e5 };
                Client c6 = new Client { FirstName = "Kati", LastName = "Szasz", Phone = "742775896", Email = "kati@gmail.com", IsDeleted = boolean, BirthYear = 1989, InsertedDate = DateTime.Now, IdentityNumber = "2970821191296", Sex = true, Inserter = e6 };
                Client c7 = new Client { FirstName = "Otto", LastName = "Szabo", Phone = "742973396", Email = "otto@gmail.com", IsDeleted = boolean, BirthYear = 1998, InsertedDate = DateTime.Now, IdentityNumber = "2970821191297", Sex = false, Inserter = e7 };
                Client c8 = new Client { FirstName = "David", LastName = "Gal", Phone = "742975006", Email = "david@gmail.com", IsDeleted = boolean, BirthYear = 1999, InsertedDate = DateTime.Now, IdentityNumber = "2970821191298", Sex = true, Inserter = e8 };
                Client c9 = new Client { FirstName = "Medea", LastName = "Kovacs", Phone = "742445896", Email = "medea@gmail.com", IsDeleted = boolean, BirthYear = 1996, InsertedDate = DateTime.Now, IdentityNumber = "2970821191299", Sex = true, Inserter = e9 };
                Client c10 = new Client { FirstName = "Mihaly", LastName = "Kelemen", Phone = "733975896", Email = "mihely@gmail.com", IsDeleted = boolean, BirthYear = 1985, InsertedDate = DateTime.Now, IdentityNumber = "29708211912910", Sex = true, Inserter = e1 };
                Client c11 = new Client { FirstName = "Levente", LastName = "Szasz", Phone = "741175896", Email = "levente@gmail.com", IsDeleted = boolean, BirthYear = 1991, InsertedDate = DateTime.Now, IdentityNumber = "2970821191281", Sex = false, Inserter = e1 };
                Client c12 = new Client { FirstName = "Alice", LastName = "Orban", Phone = "742444896", Email = "alice@gmail.com", IsDeleted = boolean, BirthYear = 1970, InsertedDate = DateTime.Now, IdentityNumber = "2970821191271", Sex = true, Inserter = e1 };

                ctx.Clients.Add(c1);
                ctx.Clients.Add(c2);
                ctx.Clients.Add(c3);
                ctx.Clients.Add(c4);
                ctx.Clients.Add(c5);
                ctx.Clients.Add(c6);
                ctx.Clients.Add(c7);
                ctx.Clients.Add(c8);
                ctx.Clients.Add(c9);
                ctx.Clients.Add(c10);
                ctx.Clients.Add(c11);
                ctx.Clients.Add(c12);

                TicketType tt1 = new TicketType { Id = 1, Name = "Havi berlet", DayNum = 30, /*OccasionNum= ,*/ Status = true, Price = 150, Description = "Egy honapos berlet, barmikor hasznalhato", StartHour = 0, EndHour = 24};
                TicketType tt2 = new TicketType { Id = 2, Name = "Havi berlet 14-16", DayNum = 30, /*OccasionNum= ,*/ Status = true, Price = 90, Description = "Egy honapos berlet, 14 es 16 ora kozott hasznalhato", StartHour = 14, EndHour = 16 };
                TicketType tt3 = new TicketType { Id = 3, Name = "Havi berlet 10-12", DayNum = 30, /*OccasionNum= ,*/ Status = true, Price = 90, Description = "Egy honapos berlet, 10 es 12 ora kozott hasznalhato", StartHour = 10, EndHour = 12 };
                TicketType tt4 = new TicketType { Id = 4, Name = "30 alkalmas",/*DayNum= 30,*/ OccasionNum = 30, Status = true, Price = 120, Description = "30 alkalmas berlet", StartHour = 0, EndHour = 24 };
                TicketType tt5 = new TicketType { Id = 5, Name = "10 alkalmas",/*DayNum= 30, */OccasionNum = 10, Status = true, Price = 75, Description = "10 alkalmas berlet", StartHour = 0, EndHour = 24 };
                TicketType tt6 = new TicketType { Id = 6, Name = "Vegyes 30", DayNum = 30, OccasionNum = 50, Status = true, Price = 150, Description = "Egy honapon kersztul barmikor hasznalhato, maximum 50 alkalommal" };

                ctx.TicketTypes.Add(tt1);
                ctx.TicketTypes.Add(tt2);
                ctx.TicketTypes.Add(tt3);
                ctx.TicketTypes.Add(tt4);
                ctx.TicketTypes.Add(tt5);
                ctx.TicketTypes.Add(tt6);

                Ticket t1 = new Ticket { Id = 1, Card = c1, BuyingDate = new DateTime(2017, 6, 24), StartDate = new DateTime(2017, 7, 1), LastLoginDate = new DateTime(2017, 7, 26), LoginsNum = 22, Price = 150, Inserter = e2, IsDeleted = false, Type = tt1 };
                Ticket t2 = new Ticket { Id = 2, Card = c1, BuyingDate = new DateTime(2017, 7, 26), StartDate = new DateTime(2017, 8, 1), LastLoginDate = new DateTime(2017, 8, 31), LoginsNum = 26, Price = 150, Inserter = e3, IsDeleted = false, Type = tt1 };
                Ticket t3 = new Ticket { Id = 3, Card = c1, BuyingDate = new DateTime(2017, 9, 1), StartDate = new DateTime(2017, 9, 1), LastLoginDate = new DateTime(2017, 9, 25), LoginsNum = 21, Price = 150, Inserter = e2, IsDeleted = false, Type = tt1 };
                Ticket t4 = new Ticket { Id = 4, Card = c1, BuyingDate = new DateTime(2017, 10, 2), StartDate = new DateTime(2017, 10, 1), LastLoginDate = new DateTime(2017, 10, 31), LoginsNum = 22, Price = 90, Inserter = e3, IsDeleted = false, Type = tt2 };
                Ticket t5 = new Ticket { Id = 5, Card = c1, BuyingDate = new DateTime(2017, 11, 1), StartDate = new DateTime(2017, 11, 1), LastLoginDate = new DateTime(2017, 11, 30), LoginsNum = 21, Price = 90, Inserter = e2, IsDeleted = false, Type = tt2 };
                Ticket t6 = new Ticket { Id = 6, Card = c1, BuyingDate = new DateTime(2017, 12, 1), StartDate = new DateTime(2017, 12, 1), LastLoginDate = new DateTime(2017, 12, 20), LoginsNum = 20, Price = 90, Inserter = e3, IsDeleted = false, Type = tt2 };
                Ticket t7 = new Ticket { Id = 7, Card = c1, BuyingDate = new DateTime(2018, 1, 8), StartDate = new DateTime(2018, 1, 1), LastLoginDate = new DateTime(2018, 1, 31), LoginsNum = 23, Price = 90, Inserter = e2, IsDeleted = false, Type = tt2 };
                Ticket t8 = new Ticket { Id = 8, Card = c1, BuyingDate = new DateTime(2018, 2, 1), StartDate = new DateTime(2018, 2, 1), LastLoginDate = new DateTime(2018, 2, 28), LoginsNum = 23, Price = 90, Inserter = e3, IsDeleted = false, Type = tt2 };
                Ticket t9 = new Ticket { Id = 9, Card = c1, BuyingDate = new DateTime(2018, 3, 1), StartDate = new DateTime(2018, 3, 1), LastLoginDate = new DateTime(2018, 3, 31), LoginsNum = 28, Price = 90, Inserter = e3, IsDeleted = false, Type = tt2 };
                Ticket t10 = new Ticket { Id = 10, Card = c1, BuyingDate = new DateTime(2018, 4, 2), StartDate = new DateTime(2018, 4, 1), LastLoginDate = new DateTime(2018, 4, 30), LoginsNum = 25, Price = 90, Inserter = e3, IsDeleted = false, Type = tt2 };
                Ticket t11 = new Ticket { Id = 11, Card = c1, BuyingDate = new DateTime(2018, 5, 1), StartDate = new DateTime(2018, 5, 1), LastLoginDate = new DateTime(2018, 5, 31), LoginsNum = 30, Price = 90, Inserter = e2, IsDeleted = false, Type = tt2 };
                Ticket t12 = new Ticket { Id = 12, Card = c1, BuyingDate = new DateTime(2018, 5, 31), StartDate = new DateTime(2018, 6, 1), LastLoginDate = new DateTime(2017, 6, 25), LoginsNum = 20, Price = 90, Inserter = e3, IsDeleted = false, Type = tt2 };

                ctx.Tickets.Add(t1);
                ctx.Tickets.Add(t2);
                ctx.Tickets.Add(t3);
                ctx.Tickets.Add(t4);
                ctx.Tickets.Add(t5);
                ctx.Tickets.Add(t6);
                ctx.Tickets.Add(t7);
                ctx.Tickets.Add(t8);
                ctx.Tickets.Add(t9);
                ctx.Tickets.Add(t10);
                ctx.Tickets.Add(t11);
                ctx.Tickets.Add(t12);

                Event ee1 = new Event { Id = 1, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 1), Type = false, Room = r, Inserter = e2};
                Event ee2 = new Event { Id = 2, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 3), Type = false, Room = r, Inserter = e2};
                Event ee3 = new Event { Id = 3, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 4), Type = false, Room = r, Inserter = e3};
                Event ee4 = new Event { Id = 4, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 5), Type = false, Room = r, Inserter = e3};
                Event ee5 = new Event { Id = 5, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 6), Type = false, Room = r, Inserter = e2};
                Event ee6 = new Event { Id = 6, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 7), Type = false, Room = r, Inserter = e2};
                Event ee7 = new Event { Id = 7, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 8), Type = false, Room = r, Inserter = e3};
                Event ee8 = new Event { Id = 8, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 10), Type = false, Room = r, Inserter = e3};
                Event ee9 = new Event { Id = 9, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 11), Type = false, Room = r, Inserter = e3};
                Event ee10 = new Event { Id = 10, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 12), Type = false, Room = r, Inserter = e2 };
                Event ee11 = new Event { Id = 11, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 13), Type = false, Room = r, Inserter = e2};
                Event ee12 = new Event { Id = 12, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 14), Type = false, Room = r, Inserter = e3};
                Event ee13 = new Event { Id = 13, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 15), Type = false, Room = r, Inserter = e3};
                Event ee14 = new Event { Id = 14, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 17), Type = false, Room = r, Inserter = e2};
                Event ee15 = new Event { Id = 15, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 18), Type = false, Room = r, Inserter = e2};
                Event ee16 = new Event { Id = 16, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 19), Type = false, Room = r, Inserter = e2};
                Event ee17 = new Event { Id = 17, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 20), Type = false, Room = r, Inserter = e2};
                Event ee18 = new Event { Id = 18, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 21), Type = false, Room = r, Inserter = e3};
                Event ee19 = new Event { Id = 19, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 22), Type = false, Room = r, Inserter = e3};
                Event ee20 = new Event { Id = 20, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 24), Type = false, Room = r, Inserter = e3};
                Event ee21 = new Event { Id = 21, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 25), Type = false, Room = r, Inserter = e3};
                Event ee22 = new Event { Id = 22, Card = c1, Ticket = t1, Date = new DateTime(2017, 7, 26), Type = false, Room = r, Inserter = e3};
                
                Event ee23 = new Event { Id = 23, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 2), Type = false, Room = r, Inserter = e3};
                Event ee24 = new Event { Id = 24, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 3), Type = false, Room = r, Inserter = e3};
                Event ee25 = new Event { Id = 25, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 4), Type = false, Room = r, Inserter = e2};
                Event ee26 = new Event { Id = 25, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 5), Type = false, Room = r, Inserter = e3};
                Event ee27 = new Event { Id = 27, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 7), Type = false, Room = r, Inserter = e2};
                Event ee28 = new Event { Id = 28, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 8), Type = false, Room = r, Inserter = e3};
                Event ee29 = new Event { Id = 29, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 9), Type = false, Room = r, Inserter = e3};
                Event ee30 = new Event { Id = 30, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 10), Type = false, Room = r, Inserter = e2};
                Event ee31 = new Event { Id = 31, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 11), Type = false, Room = r, Inserter = e2};
                Event ee32 = new Event { Id = 32, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 12), Type = false, Room = r, Inserter = e3};
                Event ee33 = new Event { Id = 33, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 14), Type = false, Room = r, Inserter = e3};
                Event ee34 = new Event { Id = 34, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 15), Type = false, Room = r, Inserter = e2};
                Event ee35 = new Event { Id = 35, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 16), Type = false, Room = r, Inserter = e3};
                Event ee36 = new Event { Id = 36, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 17), Type = false, Room = r, Inserter = e2};
                Event ee37 = new Event { Id = 37, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 18), Type = false, Room = r, Inserter = e3};
                Event ee38 = new Event { Id = 38, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 19), Type = false, Room = r, Inserter = e3};
                Event ee39 = new Event { Id = 39, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 21), Type = false, Room = r, Inserter = e3};
                Event ee40 = new Event { Id = 40, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 22), Type = false, Room = r, Inserter = e2};
                Event ee41 = new Event { Id = 41, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 23), Type = false, Room = r, Inserter = e2};
                Event ee42 = new Event { Id = 42, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 24), Type = false, Room = r, Inserter = e2};
                Event ee43 = new Event { Id = 43, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 25), Type = false, Room = r, Inserter = e2};
                Event ee44 = new Event { Id = 44, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 26), Type = false, Room = r, Inserter = e3};
                Event ee45 = new Event { Id = 45, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 28), Type = false, Room = r, Inserter = e3};
                Event ee46 = new Event { Id = 46, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 29), Type = false, Room = r, Inserter = e2};
                Event ee47 = new Event { Id = 47, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 30), Type = false, Room = r, Inserter = e3};
                Event ee48 = new Event { Id = 48, Card = c1,Ticket = t2, Date = new DateTime(2017, 8, 31), Type = false, Room = r, Inserter = e3};

                Event ee49 = new Event { Id = 49, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 1), Type = false, Room = r, Inserter = e2};
                Event ee50 = new Event { Id = 50, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 2), Type = false, Room = r, Inserter = e2};
                Event ee51 = new Event { Id = 51, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 4), Type = false, Room = r, Inserter = e3};
                Event ee52 = new Event { Id = 52, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 5), Type = false, Room = r, Inserter = e2};
                Event ee53 = new Event { Id = 53, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 6), Type = false, Room = r, Inserter = e3};
                Event ee54 = new Event { Id = 54, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 7), Type = false, Room = r, Inserter = e3};
                Event ee55 = new Event { Id = 55, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 8), Type = false, Room = r, Inserter = e3};
                Event ee56 = new Event { Id = 56, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 9), Type = false, Room = r, Inserter = e2};
                Event ee57 = new Event { Id = 57, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 11), Type = false, Room = r, Inserter = e3};
                Event ee58 = new Event { Id = 58, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 12), Type = false, Room = r, Inserter = e3};
                Event ee59 = new Event { Id = 59, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 13), Type = false, Room = r, Inserter = e2};
                Event ee60 = new Event { Id = 60, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 14), Type = false, Room = r, Inserter = e3};
                Event ee61 = new Event { Id = 61, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 15), Type = false, Room = r, Inserter = e3};
                Event ee62 = new Event { Id = 62, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 16), Type = false, Room = r, Inserter = e2};
                Event ee63 = new Event { Id = 63, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 18), Type = false, Room = r, Inserter = e3};
                Event ee64 = new Event { Id = 64, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 19), Type = false, Room = r, Inserter = e2};
                Event ee65 = new Event { Id = 65, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 20), Type = false, Room = r, Inserter = e3};
                Event ee66 = new Event { Id = 66, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 21), Type = false, Room = r, Inserter = e2};
                Event ee67 = new Event { Id = 67, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 22), Type = false, Room = r, Inserter = e3};
                Event ee68 = new Event { Id = 68, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 23), Type = false, Room = r, Inserter = e2};
                Event ee69 = new Event { Id = 69, Card = c1, Ticket = t3, Date = new DateTime(2017, 9, 25), Type = false, Room = r, Inserter = e2}; 


                ctx.Events.Add(ee1);
                ctx.Events.Add(ee2);
                ctx.Events.Add(ee3);
                ctx.Events.Add(ee4);
                ctx.Events.Add(ee5);
                ctx.Events.Add(ee6);
                ctx.Events.Add(ee7);
                ctx.Events.Add(ee8);
                ctx.Events.Add(ee9);
                ctx.Events.Add(ee10);
                ctx.Events.Add(ee11);
                ctx.Events.Add(ee12);
                ctx.Events.Add(ee13);
                ctx.Events.Add(ee14);
                ctx.Events.Add(ee15);
                ctx.Events.Add(ee16);
                ctx.Events.Add(ee17);
                ctx.Events.Add(ee18);
                ctx.Events.Add(ee19);
                ctx.Events.Add(ee20);
                ctx.Events.Add(ee21);
                ctx.Events.Add(ee22);
                ctx.Events.Add(ee23);
                ctx.Events.Add(ee24);
                ctx.Events.Add(ee25);
                ctx.Events.Add(ee26);
                ctx.Events.Add(ee27);
                ctx.Events.Add(ee28);
                ctx.Events.Add(ee29);
                ctx.Events.Add(ee30);
                ctx.Events.Add(ee31);
                ctx.Events.Add(ee32);
                ctx.Events.Add(ee33);
                ctx.Events.Add(ee34);
                ctx.Events.Add(ee35);
                ctx.Events.Add(ee36);
                ctx.Events.Add(ee37);
                ctx.Events.Add(ee38);
                ctx.Events.Add(ee39);
                ctx.Events.Add(ee40);
                ctx.Events.Add(ee41);
                ctx.Events.Add(ee42);
                ctx.Events.Add(ee43);
                ctx.Events.Add(ee44);
                ctx.Events.Add(ee45);
                ctx.Events.Add(ee46);
                ctx.Events.Add(ee47);
                ctx.Events.Add(ee48);
                ctx.Events.Add(ee49);
                ctx.Events.Add(ee50);
                ctx.Events.Add(ee51);
                ctx.Events.Add(ee52);
                ctx.Events.Add(ee53);
                ctx.Events.Add(ee54);
                ctx.Events.Add(ee55);
                ctx.Events.Add(ee56);
                ctx.Events.Add(ee57);
                ctx.Events.Add(ee58);
                ctx.Events.Add(ee59);
                ctx.Events.Add(ee60);
                ctx.Events.Add(ee61);
                ctx.Events.Add(ee62);
                ctx.Events.Add(ee63);
                ctx.Events.Add(ee64);
                ctx.Events.Add(ee65);
                ctx.Events.Add(ee66);
                ctx.Events.Add(ee67);
                ctx.Events.Add(ee68);
                ctx.Events.Add(ee69);
                
                ctx.SaveChanges();
            }
        }
    }
}
